[project]
name = "pynamo"
version = "0.1.0"
description = "A dynamodb ORM"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.uv]
dev-dependencies = [
    "ipython>=8.18.1",
    "pytest-coverage>=0.0",
    "pytest>=8.3.5",
]

[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

