[project]
name = "pynamo"
version = "0.1.0"
description = "A dynamodb ORM"
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[tool.uv]
dev-dependencies = [
    "mypy>=1.4.1",
    "pytest-coverage>=0.0",
    "pytest>=7.4.4",
]

[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

